security:
  oauth2:
    client:
      registrations:
        github:
          client-id: ${GITHUB_CLIENT_ID}
          client-secret: ${GITHUB_CLIENT_SECRET}
        facebook:
          client-id: ${FACEBOOK_CLIENT_ID}
          client-secret: ${FACEBOOK_CLIENT_SECRET}